import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useSession, signIn } from "next-auth/react";
import {
  AppBar,
  Button,
  Grid,
  Toolbar,
  Typography,
  Box,
  ButtonBase,
} from "@mui/material";
import { styled } from "@mui/material/styles";

export default function Home() {
  const { data: session } = useSession();
  const categories = [
    "Kadın",
    "Erkek",
    "Çocuk",
    "Giyim",
    "Ayakkabı",
    "Aksesuar",
  ];
  const images = [
    {
      url: "/assets/images/woman.jpeg",
      title: "Kadın",
      width: "40%",
    },
    {
      url: "/assets/images/man.jpeg",
      title: "Erkek",
      width: "30%",
    },
    {
      url: "/assets/images/child.png",
      title: "Çocuk",
      width: "30%",
    },
  ];
  const ImageButton = styled(ButtonBase)(({ theme }) => ({
    position: "relative",
    height: 200,
    [theme.breakpoints.down("sm")]: {
      width: "100% !important", // Overrides inline-style
      height: 100,
    },
    "&:hover, &.Mui-focusVisible": {
      zIndex: 1,
      "& .MuiImageBackdrop-root": {
        opacity: 0.15,
      },
      "& .MuiImageMarked-root": {
        opacity: 0,
      },
      "& .MuiTypography-root": {
        border: "4px solid currentColor",
      },
    },
  }));
  const ImageSrc = styled("span")({
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundSize: "cover",
    backgroundPosition: "center 40%",
  });

  const Image = styled("span")(({ theme }) => ({
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: theme.palette.common.white,
  }));

  const ImageBackdrop = styled("span")(({ theme }) => ({
    position: "absolute",
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    backgroundColor: theme.palette.common.black,
    opacity: 0.4,
    transition: theme.transitions.create("opacity"),
  }));

  const ImageMarked = styled("span")(({ theme }) => ({
    height: 3,
    width: 18,
    backgroundColor: theme.palette.common.white,
    position: "absolute",
    bottom: -2,
    left: "calc(50% - 9px)",
    transition: theme.transitions.create("opacity"),
  }));
  return (
    // <div className={styles.container}>
    <div style={{ width: "100%" }}>
      <Head>
        <title>E-Ticaret Uygulaması</title>
        <meta name="description" content="Generated by create next app" />
        <link
          rel="icon"
          href="https://media.licdn.com/dms/image/C4E0BAQGk5zrzwIAO1A/company-logo_200_200/0/1592143937192?e=2147483647&v=beta&t=rTP5oelZWTKsnFInOdGKWlbKYFEV_5Et07yEKY6RQF0"
        />
      </Head>
      {/* {session ? (
        <h3>You are signed in</h3>
      ) : (
        <>
          <h3>You are not signed in</h3>
          <button onClick={() => signIn()}>Sign In</button>
        </>
      )} */}
      <div>
        <Grid bgcolor="white" container>
          <AppBar position="static" sx={{ backgroundColor: "white" }}>
            <Toolbar>
              {categories.map((category) => (
                <Typography
                  color="black"
                  variant="h6"
                  component="div"
                  margin="0 20px 0 0"
                >
                  <Button sx={{ color: "black" }}>{category}</Button>
                </Typography>
              ))}
            </Toolbar>
          </AppBar>
          <Box
            sx={{
              display: "flex",
              flexWrap: "wrap",
              minWidth: 300,
              width: "100%",
              height: "700px",
            }}
          >
            {images.map((image) => (
              <ImageButton
                focusRipple
                key={image.title}
                style={{
                  width: image.width,
                  height: "auto",
                }}
              >
                <ImageSrc style={{ backgroundImage: `url(${image.url})` }} />
                <ImageBackdrop className="MuiImageBackdrop-root" />
                <Image>
                  <Typography
                    component="span"
                    variant="subtitle1"
                    color="inherit"
                    sx={{
                      position: "relative",
                      p: 4,
                      pt: 2,
                      pb: (theme) => `calc(${theme.spacing(1)} + 6px)`,
                    }}
                  >
                    {image.title}
                    <ImageMarked className="MuiImageMarked-root" />
                  </Typography>
                </Image>
              </ImageButton>
            ))}
          </Box>
        </Grid>
      </div>
    </div>
  );
}
