import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>E-Ticaret Uygulaması</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://media.licdn.com/dms/image/C4E0BAQGk5zrzwIAO1A/company-logo_200_200/0/1592143937192?e=2147483647&v=beta&t=rTP5oelZWTKsnFInOdGKWlbKYFEV_5Et07yEKY6RQF0" />
      </Head>
    </div>
  )
}
